#!/usr/bin/env python3
"""Build `config/phenotype/<cohort>_phenotype.csv` from a dataset's own table.

    # ds002837 -- OpenNeuro ships participants.tsv with the raw dataset
    python tools/make_phenotype.py --cohort ds002837 \
        --source /path/to/ds002837/participants.tsv \
        --sub-column participant_id --age-column age --sex-column sex

    # Cam-CAN ccfrail -- age and frailty are the point of this cohort
    python tools/make_phenotype.py --cohort camcan_ccfrail \
        --source /path/to/camcan/ccfrail_phenotype.tsv \
        --sub-column CCID --age-column Age --sex-column Sex \
        --sex-map "1=M,2=F" --keep frailty_index,gait_speed,grip_strength

    # a second table for the same cohort, joined onto the first on `sub`
    python tools/make_phenotype.py --cohort camcan --source scores.tsv \
        --sub-column CCID --keep MMSE --merge

WHY THIS IS A TOOL AND NOT A JOIN IN A NOTEBOOK
-----------------------------------------------
Age, sex and clinical scores are in NONE of the files this pipeline reads or
writes. `config/*_participants.csv` is generated by `make_participants.py` from
what discovery finds on disk and carries curation only -- participant_id, sub,
cohort, task, excluded, exclusion_reason. `participants_qc.csv` is measurement
written by `diagnose`. Neither has ever contained a phenotype.

So the phenotype has to be imported, once, from each dataset's own source
table, and those tables disagree about everything: the id column is
`participant_id` in one and `CCID` in another, sex is `M`/`F` here and `1`/`2`
there, and Cam-CAN's scores live in files that are not distributed with the
imaging data at all. Doing that inline in a notebook means the mapping is
re-decided every time someone re-runs a cell.

The output is a plain CSV, checked in next to the participants tables, with one
row per subject and a fixed core schema:

    sub, cohort, age, sex, <any --keep columns, verbatim>

WHAT IT REFUSES TO GUESS
------------------------
Numeric sex codes. `1` is male in Cam-CAN's tables and female in others; a
tool that picks one is a tool that silently flips a covariate. Strings it does
normalise, because `M`/`m`/`male`/`MALE` are unambiguous. Anything else is
carried through verbatim and reported, and `--sex-map` is how you state a
numeric coding explicitly.

It also does not invent rows. Coverage against the cohort's participants table
is printed, including which subjects got no phenotype -- a partial phenotype is
normal (Cam-CAN's frailty tables do not cover every CC700 subject) and is
supposed to be visible rather than inferred later from a column of NaNs.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

CORE = ["sub", "cohort", "age", "sex"]

# Unambiguous string codings only. Numeric codings need --sex-map.
SEX_STRINGS = {
    "m": "M", "male": "M", "man": "M",
    "f": "F", "female": "F", "woman": "F",
}


def normalise_sub(value) -> str:
    """`sub-CC110033` / `CC110033` / `1` -> the bare id used as the `sub=` key.

    Kept as a string throughout: `sub=01` read as an integer is exactly the bug
    the partition keys are all-string to avoid, and it destroys `CC110033` too.
    """
    s = str(value).strip()
    return s.removeprefix("sub-")


def normalise_sex(value, sex_map: dict[str, str]) -> tuple[str, bool]:
    """Returns (value, recognised). Unrecognised values are kept, not blanked."""
    if value is None:
        return "", True
    s = str(value).strip()
    if not s or s.lower() in ("nan", "n/a", "na"):
        return "", True
    if s in sex_map:
        return sex_map[s], True
    if s.lower() in SEX_STRINGS:
        return SEX_STRINGS[s.lower()], True
    return s, False


def parse_sex_map(text: str | None) -> dict[str, str]:
    if not text:
        return {}
    out = {}
    for item in text.split(","):
        if "=" not in item:
            raise SystemExit(f"--sex-map entry {item!r} is not CODE=LABEL")
        code, label = item.split("=", 1)
        out[code.strip()] = label.strip()
    return out


def read_source(path: Path, sep: str | None):
    import pandas as pd

    if sep is None:
        sep = "\t" if path.suffix.lower() in (".tsv", ".tab") else ","
    return pd.read_csv(path, sep=sep, dtype=str, keep_default_na=False, na_values=[""])


def participants_subs(cohort: str) -> tuple[set[str], Path | None]:
    """The subjects this cohort actually has, from its participants CSV."""
    import pandas as pd

    for path in sorted((REPO / "config").glob("*_participants.csv")):
        df = pd.read_csv(path, dtype=str)
        if cohort in set(df.get("cohort", pd.Series(dtype=str)).dropna()):
            return set(df.loc[df["cohort"] == cohort, "sub"].astype(str)), path
    return set(), None


def main(argv=None) -> int:
    import pandas as pd

    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--cohort", required=True,
                   help="cohort key, matching `cohort:` in the config")
    p.add_argument("--source", required=True, help="the dataset's own table (tsv/csv)")
    p.add_argument("--sub-column", required=True,
                   help="column holding the subject id ('sub-' prefix optional)")
    p.add_argument("--age-column")
    p.add_argument("--sex-column")
    p.add_argument("--sex-map", metavar="CODE=LABEL,...",
                   help="explicit coding for a numeric sex column, e.g. '1=M,2=F'. "
                        "Required for numeric codes: this tool will not guess one.")
    p.add_argument("--keep", default="",
                   help="comma-separated extra columns to carry through verbatim "
                        "(clinical scores, frailty index, group labels)")
    p.add_argument("--sep", help="source delimiter; inferred from the suffix otherwise")
    p.add_argument("-o", "--out", help="default config/phenotype/<cohort>_phenotype.csv")
    p.add_argument("--merge", action="store_true",
                   help="outer-join onto an existing file on `sub` instead of "
                        "replacing it, for a cohort whose phenotype is split "
                        "across several source tables")
    p.add_argument("--force", action="store_true", help="overwrite an existing file")
    p.add_argument("--restrict-to-participants", action="store_true",
                   help="drop source rows for subjects not in this cohort "
                        "(Cam-CAN's tables cover the whole archive, not one cohort)")
    args = p.parse_args(argv)

    src = Path(args.source)
    if not src.exists():
        print(f"source not found: {src}", file=sys.stderr)
        return 1
    out = Path(args.out) if args.out else (
        REPO / "config" / "phenotype" / f"{args.cohort}_phenotype.csv")
    if out.exists() and not (args.force or args.merge):
        print(f"refusing to overwrite {out}\n"
              f"  --merge joins a second source onto it; --force replaces it.",
              file=sys.stderr)
        return 1

    raw = read_source(src, args.sep)
    keep = [c.strip() for c in args.keep.split(",") if c.strip()]
    wanted = [args.sub_column] + [c for c in (args.age_column, args.sex_column) if c] + keep
    missing = [c for c in wanted if c not in raw.columns]
    if missing:
        print(f"{src} has no column(s) {missing}.\n  Columns present: "
              f"{list(raw.columns)}", file=sys.stderr)
        return 1

    df = pd.DataFrame({"sub": raw[args.sub_column].map(normalise_sub)})
    df["cohort"] = args.cohort

    if args.age_column:
        age = pd.to_numeric(raw[args.age_column], errors="coerce")
        n_bad = int(age.isna().sum() - raw[args.age_column].isna().sum())
        if n_bad:
            print(f"  {n_bad} non-numeric age value(s) -> NaN")
        df["age"] = age
    if args.sex_column:
        sex_map = parse_sex_map(args.sex_map)
        pairs = [normalise_sex(v, sex_map) for v in raw[args.sex_column]]
        df["sex"] = [v for v, _ in pairs]
        unknown = sorted({v for (v, ok) in pairs if not ok and v})
        if unknown:
            print(f"  sex values carried through unrecognised: {unknown}\n"
                  f"    If these are codes, re-run with --sex-map "
                  f"\"{unknown[0]}=...\" so the coding is written down.")
    for col in keep:
        df[col] = raw[col]

    dupes = df["sub"].duplicated()
    if dupes.any():
        print(f"  {int(dupes.sum())} duplicate subject row(s) in the source, "
              f"keeping the first: {sorted(df.loc[dupes, 'sub'])[:5]}")
        df = df[~dupes]

    cohort_subs, part_path = participants_subs(args.cohort)
    if args.restrict_to_participants:
        if not cohort_subs:
            print(f"--restrict-to-participants: no participants CSV found for "
                  f"cohort={args.cohort!r}", file=sys.stderr)
            return 1
        before = len(df)
        df = df[df["sub"].isin(cohort_subs)]
        print(f"  restricted {before} -> {len(df)} row(s) to subjects in "
              f"{part_path.name}")

    if args.merge and out.exists():
        old = pd.read_csv(out, dtype={"sub": str})
        shared = [c for c in df.columns if c in old.columns and c != "sub"]
        # New values win only where they are not null, so a second table adding
        # one score cannot blank an age the first table already supplied.
        merged = old.merge(df, on="sub", how="outer", suffixes=("", "_new"))
        for col in shared:
            if f"{col}_new" in merged:
                merged[col] = merged[col].combine_first(merged[f"{col}_new"])
                merged = merged.drop(columns=[f"{col}_new"])
        df = merged
        print(f"  merged onto {len(old)} existing row(s) -> {len(df)}")

    ordered = [c for c in CORE if c in df.columns]
    df = df[ordered + [c for c in df.columns if c not in ordered]]
    df = df.sort_values("sub", ignore_index=True)

    out.parent.mkdir(parents=True, exist_ok=True)
    tmp = out.with_name(out.name + ".tmp")
    df.to_csv(tmp, index=False)
    tmp.replace(out)
    print(f"wrote {out}  ({len(df)} row(s), columns: {list(df.columns)})")

    if cohort_subs:
        have = set(df["sub"])
        covered = cohort_subs & have
        absent = sorted(cohort_subs - have)
        print(f"\ncoverage against {part_path.name}: "
              f"{len(covered)}/{len(cohort_subs)} subject(s) have a phenotype row")
        if absent:
            print(f"  {len(absent)} with none: {absent[:10]}"
                  + (" ..." if len(absent) > 10 else ""))
            print("  These will join as NaN. That is a real gap in the cohort, "
                  "not a bug -- carry it into any model that uses these columns.")
        extra = sorted(have - cohort_subs)
        if extra:
            print(f"  {len(extra)} phenotype row(s) for subjects not in this "
                  f"cohort, kept: {extra[:5]}"
                  + (" ..." if len(extra) > 5 else "")
                  + "\n  Use --restrict-to-participants to drop them.")
    else:
        print(f"\nno participants CSV for cohort={args.cohort!r}; coverage not checked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
